### PR TITLE
(IsaacG) Refactored to Hell and Back

### PR DESCRIPTION
**Pull request by King-Drake**
The changes, oh man the changes.
I got rid of externs.h and includes.h
I added about 70 new files
I added new instances of type safety
The only issue is that I don't know how many changes have been made since I downloaded the repo.

### CODE REVIEW

**Comment by rardiol** [comment]
Looks big, too bad I couldn't get it to compile so I can see it. I think list of new features and a version bump would be nice.

Made couple of commits here : https://github.com/rardiol/Liberal-Crime-Squad/tree/kdi. One does CRLF -> LF, which makes clearer up what actually changed, it's "only" 16k additions and 2k removals. The other does forward slashes in includes so I can compile in Linux.

I can't compile due to a lot of "Liberal-Crime-Squad/src/./common.h:143: undefined reference to `gchar'"

Do all new binaries like workspaces/Release/SDL2.dll or workspaces/Release/art/newscast.cmv workspaces/Release/art/newspic.cpc actually belong? What are cmv and cpc anyway?

**Comment by King-Drake** [comment]
Can't compile?  Drat, I was afraid of that.
I've no idea what the "cmv" and "cpc" are, I didn't intend to add those.
IIRC, remove the files "common.h", "includes.h" and "externs.h", that should fix most of the problems.
I'm new to github, so I'm afraid I don't know much about what I did, or how I should have done it.
As for changelog, I mostly refactored to reduce inter file dependencies.
The changes are that I extracted much of the text into external data files in the art directory (the various sub-directories I added).

**Comment by King-Drake** [comment]
This is the folder I compile from.  I use visual studio 2015, and so the makefile is not updated (since Microsoft evidently decided they didn't need to support automatic generation of makefiles).
Hopefully this will be more straightforward.

http://www.mediafire.com/download/qw6h02pizcj0hc8/v4.10.0+-+Copy+%284%29+Finally+Finished+Refactoring.zip

I've been working on this for a while, and I kind of want my eyes to stop hurting when I blink, j/k.

**Comment by Kamal-Sadek** [comment]
Still taking a look at all the changes. Will update during the weekend!

**Comment by King-Drake** [comment]
No hurry.  If there's anything I can do to help the process along.... because I kinda learned how to do this while I was doing it, so the files early in the alphabet aren't refactored as well as the later ones.

**Comment by Kamal-Sadek** [comment]
Sorry for the very late reply. Unfortunately, I'm going to have to not merge this. The main issue is that there's _too_ many changes for me to look at and just add my "seal of approval" in terms of bugs and the like. I highly encourage you to continue work on your own fork, however. It seems like there's a lot of good stuff in here!

**Pull request closed without merging**
